version: '3'
services:
  clustering:
    build: .
    image: clusterbackend.azurecr.io/clustering
    ports:
      - "80:80"

  redis:
    image: bitnami/redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: unless-stopped
    ports:
      - "6379:6379"

  worker:
    build: .
    image: clusterbackend.azurecr.io/clustering
    command: make handler
    depends_on:
      - clustering
      - redis