version: '3'
services:
  mongodb:
    image: bitnami/mongodb
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/bitnami/mongodb

  clustering:
    build: .
    depends_on:
      - mongodb
    image: clusterbackend.azurecr.io/clustering
    ports:
      - "8001:80"

  redis:
    image: bitnami/redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: unless-stopped
    ports:
      - "6379:6379"

  worker:
    build: .
    image: clusterbackend.azurecr.io/clustering
    command: make handler
    depends_on:
      - clustering
      - redis

volumes:
  mongodb:
  redis: