[default]
ALLOWED_ORIGINS = ["http://localhost:5173", "https://thesis-cluster.netlify.app/"]
API_URL = "http://clustering:80"
CELERY_BROKER_URL = "redis://redis:6379/0"
CELERY_RESULT_BACKEND = "redis://redis:6379/0"
INTERNAL_TOKEN = "default_token"
MONGO_DSN = "mongodb://mongodb:27017/ClusteringDB"
JWT_SECRET_KEY = ""
JWT_ALGORITHM = "HS256"